# Generated by Django 3.2.5 on 2021-08-19 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ]
        ),
        migrations.CreateModel(
            name='SharedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(blank=True, max_length=255)),
                ('maxTokens', models.IntegerField(default=0)),
                ('stop', models.JSONField(default=dict)),
                ('prompt', models.CharField(blank=True, max_length=255)),
                ('temperature', models.IntegerField(default=0)),
                ('topP', models.IntegerField(default=0)),
                ('presencePenalty', models.IntegerField(default=0)),
                ('frequencyPenalty', models.IntegerField(default=0)),
                ('examples', models.JSONField(default=dict)),
            ],
        ),
    ]
