# Generated by Django 3.2.5 on 2021-12-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedprompt',
            name='best_of',
            field=models.IntegerField(default=0),
        ),
    ]
