# Generated by Django 3.2.5 on 2021-08-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=255)),
                ('table', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
            ],
        ),
    ]
