# Generated by Django 3.2.5 on 2021-08-17 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_custommodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.0, help_text='Temperature', max_digits=5)),
                ('max_tokens', models.DecimalField(decimal_places=2, default=0.0, help_text='Max Tokens', max_digits=5)),
                ('top_p', models.DecimalField(decimal_places=2, default=0.0, help_text='Top P', max_digits=5)),
                ('n', models.IntegerField(default=1)),
                ('presence_penalty', models.DecimalField(decimal_places=2, default=0.0, help_text='Presence Penalty', max_digits=5)),
                ('frequency_penalty', models.DecimalField(decimal_places=2, default=0.0, help_text='Frequency Penalty', max_digits=5)),
                ('stop', models.JSONField(default=dict)),
                ('prompt', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_model', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.custommodel')),
            ],
            options={
                'db_table': 'workspace',
            },
        ),
    ]
