# Generated by Django 3.2.5 on 2021-12-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_sharedprompt_best_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='best_of',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharedprompt',
            name='best_of',
            field=models.IntegerField(default=1),
        ),
    ]
