# Generated by Django 3.2.5 on 2021-08-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_workspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='stop',
            new_name='stop_symbols',
        ),
        migrations.AlterField(
            model_name='workspace',
            name='custom_model',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='restapi.custommodel'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
