# Generated by Django 3.2.5 on 2021-12-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_airtableworkspace'),
        ('restapi', '0003_auto_20211213_0759'),
    ]

    operations = [
    ]