# Generated by Django 3.2.5 on 2021-08-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20210824_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='airtable_api_key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workspace',
            name='airtable_base',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workspace',
            name='airtable_table',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workspace',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
