# Generated by Django 3.2.5 on 2021-08-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20210827_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='airtable_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
