# Generated by Django 3.2.5 on 2021-09-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_workspace_airtable_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirtableWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default='', max_length=255)),
                ('soruce_table', models.CharField(default='', max_length=255)),
                ('destination_base', models.CharField(default='', max_length=255)),
                ('destination_table', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'restapi_airtable_workspace',
            },
        ),
    ]
